### ISSUE TITLE
Plugin does not receive push notifications in the development configuration

### ISSUE THREAD

**Issue by masahirotanaka** [KiiPlatform/kii-cordova-plugin#12]
It appears that the plugin only registers app as `production`, which results in the app only receiving for the release build.

https://github.com/KiiPlatform/kii-cordova-plugin/blob/82dec4b42b9897d4ba8d93d42265eae452a24f4b/src/ios/KiiPush.m#L179

I think it should handle in both builds so that users can also check push notifications during their development.

**Comment by satoshikumano** [comment]
done. #16
