### ISSUE TITLE
Document errors

### ISSUE THREAD

**Issue by masahirotanaka** [KiiPlatform/kii-cordova-plugin#13]
Some trivial document errors we found so far:

1. http://documentation.kii.com/ja/guides/javascript/managing-push-notification/push-to-user/subscribing-topic/

  `var topic = KiiUser.getCurrentUser().topicWithName();`

  should be

  `var topic = KiiUser.getCurrentUser().topicWithName(topicName);`

2. http://documentation.kii.com/ja/guides/javascript/managing-push-notification/push-to-user/checking-subscription/

  Missing `function()` in the callbacks.

**Comment by makoto-iguchi** [comment]
Thanks for the feedback.
The docs are fixed now.

**Comment by masahirotanaka** [comment]
Thanks! :+1:
